CREATE TABLE IF NOT EXISTS users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                             NOT NULL,
    email VARCHAR(512)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description TEXT,
    available   BOOLEAN                                  NOT NULL,
    owner_id    INTEGER                                  NOT NULL,
    request_id  INTEGER,

    CONSTRAINT pk_item PRIMARY KEY (id),

    CONSTRAINT fk_item_owner
        FOREIGN KEY (owner_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP                                NOT NULL,
    end_date   TIMESTAMP                                NOT NULL,
    item_id    INTEGER                                  NOT NULL,
    booker_id  INTEGER                                  NOT NULL,
    status     VARCHAR(32)                              NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booking_item
        FOREIGN KEY (item_id)
            REFERENCES items (id),
    CONSTRAINT fk_booking_booker
        FOREIGN KEY (booker_id)
            REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  TEXT                                     NOT NULL,
    requestor_id INTEGER                                  NOT NULL,
    created      TIMESTAMP                                NOT NULL,
    CONSTRAINT pk_item_request PRIMARY KEY (id),
    CONSTRAINT fk_requestor
        FOREIGN KEY (requestor_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(1000) NOT NULL,
    item_id   INTEGER       NOT NULL,
    author_id INTEGER       NOT NULL,
    created   TIMESTAMP     NOT NULL,
    CONSTRAINT fk_comment_item
        FOREIGN KEY (item_id)
            REFERENCES items (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_comment_author
        FOREIGN KEY (author_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);